/**
 * @author Midware
 * @Website www.midware.net
 * @Developer Reinaldo Stephens Chaves
 * @contact contact@midware.net
 */
define(["require", "exports", "N/ui/serverWidget", "N/search", "N/record", "N/log"], function (require, exports, serverWidget, search, record, log) {
    Object.defineProperty(exports, "__esModule", { value: true });
    exports.CANCEL_WITHDRAWAL_FORM = exports.CLOSED_STATUS_FORM = exports.PENDING_AWAITING_CONTRACT_FORM = exports.BACK_ON_MARKET_FORM = exports.AVAILABLE_TO_PENDING_FORM = exports.PROCEED_FORM_DEFAULT = exports.FORM = exports.INTERNAL_ID_HIDDEN_FIELD = exports.PROPERTY_RECORD = exports.SALES_STATUS_LIST = exports.OK_FORM = exports.SUCCESS_DEFAULT_FORM = exports.SUCCESS_PENDING_TO_AVAILABLE_FORM = exports.FORMS = exports.SUBMITTER = exports.FOLDER_ID = exports.CLIENT_SCRIPT_PATH_UE = exports.CLIENT_SCRIPT_PATH = exports.SUITELET_SCRIPT_ID = exports.source = exports.urlSource = void 0;
    exports.source = {
        source: ""
    };
    exports.SUITELET_SCRIPT_ID = "717"; //502 in Sandbox
    exports.CLIENT_SCRIPT_PATH = "../../ClientScripts/UpdateFormFieldsDinamicallyCS.js";
    exports.CLIENT_SCRIPT_PATH_UE = "../ClientScripts/UpdateFormFieldsDinamicallyCS.js";
    var FOLDER_ID = function (pPropertyRecord) {
        try {
            var builderId = pPropertyRecord.getValue(exports.PROPERTY_RECORD.builderDivision);
            var builderFolderId = search.lookupFields({
                type: search.Type.CUSTOMER,
                id: builderId,
                columns: ["custentity_mw_root_folder"],
            });
            var rootFolder = builderFolderId["custentity_mw_root_folder"];
            var houseNumber = pPropertyRecord.getValue(exports.PROPERTY_RECORD.houseNum);
            var streetName = pPropertyRecord.getText(exports.PROPERTY_RECORD.streetNaam);
            var forlderName = "".concat(houseNumber, " ").concat(streetName).trim();
            var propertyFolder = getPropertyFolder(forlderName, rootFolder);
            return propertyFolder;
        }
        catch (error) {
            log.error("Error getting folderid", "Error getting folderid : ".concat(error.message, "\n\nReturning folder id 41 (Sales Contracts)"));
            log.debug("Error getting folderid", JSON.stringify(error));
            return 41;
        }
    };
    exports.FOLDER_ID = FOLDER_ID;
    exports.SUBMITTER = {
        ok: "OK",
        proceed: "Proceed",
        submit: "Submit",
    };
    exports.FORMS = {
        availableToPending: 1,
        pendingToAvailable: 2,
        availableToPendingAwaitingContract: 3,
        pendingOrPendingAwaitingContractToAvailable: 4,
        availableOrPendingToWithdrawnOrCanceled: 5,
    };
    exports.SUCCESS_PENDING_TO_AVAILABLE_FORM = {
        success: {
            id: "success",
            label: "The property has been changed from Pending to Available.",
            source: null,
            type: serverWidget.FieldType.TEXT,
            disabled: false,
        },
        okButton: {
            id: "custpage_ok",
            label: "OK",
        },
    };
    exports.SUCCESS_DEFAULT_FORM = {
        success: {
            id: "success",
            label: "Property Successfully Updated.",
            source: null,
            type: serverWidget.FieldType.TEXT,
            disabled: false,
        },
        okButton: {
            id: "custpage_ok",
            label: "OK",
        },
    };
    exports.OK_FORM = {
        property: {
            id: "custpage_housenumber",
            label: "Property",
            source: "customrecord_property_record",
            type: serverWidget.FieldType.SELECT,
            disabled: false,
        },
        urlSource: {
            id: "custpage_url_source",
            label: "URL Source",
            source: null,
            type: serverWidget.FieldType.TEXT,
            disabled: false,
            //hidden: true,
        },
        hiddenField: {
            id: "company_cust_hidden",
            label: "Hidden",
            source: null,
            type: serverWidget.FieldType.TEXT,
            disabled: false,
        },
        submitButton: {
            label: "Sale Status Change Form",
        },
    };
    exports.SALES_STATUS_LIST = {
        available: { value: "1", text: "Available" },
        pending: { value: "2", text: "Pending" },
        closed: { value: "3", text: "Closed" },
        withdrawn: { value: "4", text: "Withdrawn" },
        expired: { value: "5", text: "Expired" },
        awaitingEntryIntoMLS: { value: "6", text: "Awaiting Entry Into MLS" },
        canceled: { value: "7", text: "Canceled" },
        pendingAwaitingContract: {
            value: "8",
            text: "Pending (Awaiting Contract)",
        },
        closedAwaitingHUD: { value: "9", text: "Closed (Awaiting HUD)" },
        soldCanceledBeforeListed: {
            value: "10",
            text: "Sold/Canceled Before Listed",
        },
    };
    // Property record data
    exports.PROPERTY_RECORD = {
        actualClosingDate: "custrecord_actual_closing_date",
        additinalRealEstateAgentRole: "custrecord_mw_additional_agent_role",
        additonalRealEstateAgentId: "custrecord_additional_selling_agent_id",
        additonalRealEstateAgentIdFreeForm: "custrecord_additional_agent_id_free_form",
        additonalRealEstateAgentName: "custrecord_additional_agent_record",
        additonalRealEstateAgentNameFreeForm: "custrecord_mw_additional_agent",
        address: "custrecord_simple_name",
        administrativeContact: "custrecord17",
        administrativeContactEmail: "custrecord18",
        administrativeContactPhone: "custrecord19",
        brokerageId: "custrecord_real_estate_broker_id_mls1",
        brokerageName: "custrecord_real_estate_broker_name",
        brokerageNameFreeForm: "custrecord_brokerage_name_sn",
        builderDivision: "custrecord12",
        buyersName: "custrecord_buyers_last_name",
        closedPrintfull1: "custrecord_closed_printfull1",
        closedPrintfull2: "custrecord_closed_printfull2",
        closingNotes: "custrecord_closing_notes",
        closingNotifyDate1: "custrecord_closing_date_mls_region1",
        closingNotifyDate2: "custrecord_closing_date_mls_region2",
        closingPrice: "custrecord50",
        concessions: "custrecord_concessions",
        constructionStatusAtContract: "custrecord_construction_status_contract",
        constructionStatusList: "custrecord_construction_status_listing",
        contractApprovalDate: "custrecord_contract_approval_date",
        contractReceiveFromBuilder: "custrecord_contract_received_date",
        currentConstructionStatus: "custrecord_current_construction",
        currentListPrice: "custrecord_current_list_price",
        divisionManager: "custrecord29",
        divisionManagerEmail: "custrecordprop_division_mgr_email",
        elevation: "custrecord_elevation",
        enterSaleAsTeam: "custrecord_mw_enter_as_team",
        estimateCompletionDate: "custrecord_estimated_completion_date",
        estimatedClosingPrice: "custrecord_estimated_closing_price",
        estimateRoofDate: "custrecord_estimated_under_roof_date",
        expirationDate: "custrecord_expiration_date",
        estimatedClosingDate: "custrecord_estimated_closing_date",
        financingType: "custrecord_financing_type",
        floorplan: "custrecord_floorplan",
        houseNum: "custrecord_house_number",
        hud1: "custrecord_hud1",
        hudRcvdDate: "custrecord_hud_received_date",
        internalid: "internalid",
        isinactive: "isinactive",
        lastConstUpdate: "custrecord_property_date_const_update",
        lender: "custrecord_financing_company",
        listDate: "custrecord_list_date",
        listingType: "custrecord_listing_type",
        listingNotes: "custrecord_listing_notes",
        listNotifyMlsRegion1: "custrecord_listing_date_mls_region1",
        listNotifyMlsRegion2: "custrecord_listing_date_mls_region2",
        loanAmount: "custrecord_loan_amount",
        lotNumber: "custrecord_lot_number",
        mlsNumberRegion1: "custrecord_mls_number_region1",
        mlsNumberRegion2: "custrecord_mls_number_region2",
        mlsRegion1: "custrecord15",
        mlsRegion2: "custrecord16",
        name: "name",
        originalListPrice: "custrecord_original_listing_price",
        pendingNotificationDateMLSRegion1: "custrecord_pending_date_mls_region1",
        pendingNotificationDateMLSRegion2: "custrecord_pending_date_mls_region2",
        pendingPrintfull1: "custrecord_pending_printfull1",
        pendingPrintfull2: "custrecord_pending_printfull2",
        primaryAgentIdFreeForm: "custrecord_primary_agent_id_free_form",
        primaryRealEstateAgentId: "custrecord_real_estate_agent_id_region_1",
        primaryRealEstateAgentName: "custrecord_real_estate_agent_name",
        primaryRealEstateAgentNameFreeForm: "custrecord_agent_name_sn",
        propertyDateSalesStatusUpdate: "custrecord_property_date_sales_st_update",
        propertyPhotos: "custrecord_property_photos",
        purchaseContact: "custrecord_purchase_contract",
        resendClosingNotif: "custrecord_resend_closing_notification",
        salesManager: "custrecord28",
        salesManagerEmail: "custrecord_prop_sales_mgr_email",
        salesNotes: "custrecord_sale_notes",
        saleSubmittedBy: "custrecord_mw_sale_submitted_by",
        sellerPaidClosingCosts: "custrecord_seller_paid_closing_costs",
        sellingAgentComments: "custrecord_selling_agent_comments",
        sellingBsr: "custrecord_selling_bsr",
        sellingTeamName: "custrecord_selling_team_name",
        squareFeet: "custrecord_square_feet",
        status: "custrecord_property_status",
        streetNaam: "custrecord31",
        subdivisionName: "custrecordcustrecordsubdname",
        type: "customrecord_property_record",
    };
    exports.INTERNAL_ID_HIDDEN_FIELD = {
        internalid: {
            id: "custpage_internalid",
            label: "internalid",
            source: null,
            type: serverWidget.FieldType.TEXT,
            disabled: false,
            relatedField: exports.PROPERTY_RECORD.internalid,
        },
    };
    // Change Property Status Form data
    exports.FORM = {
        sourceField: {
            id: "custpage_url_source",
            label: "Source",
            source: null,
            type: serverWidget.FieldType.TEXT,
            disabled: false,
            //displayType: serverWidget.FieldDisplayType.HIDDEN,
        },
        messageField: {
            id: "custpage_abhi_msg",
            label: "Message",
            source: null,
            type: serverWidget.FieldType.INLINEHTML,
            disabled: false,
        },
        propertyField: {
            id: "custpage_housenumber",
            label: "Property",
            source: "customrecord_property_record",
            type: serverWidget.FieldType.SELECT,
            displayType: serverWidget.FieldDisplayType.DISABLED,
            disabled: true,
        },
        urlSource: {
            id: "custpage_url_source",
            label: "URL Source",
            source: null,
            type: serverWidget.FieldType.TEXT,
            disabled: false,
            //hidden: true,
        },
        newStatusField: {
            id: "custpage_status",
            label: "Status",
            source: null,
            type: serverWidget.FieldType.SELECT,
            disabled: false,
        },
        currentStatusField: {
            id: "custpage_oldstatus",
            label: "Current Status",
            source: "customlist31",
            type: serverWidget.FieldType.SELECT,
            displayType: serverWidget.FieldDisplayType.DISABLED,
            disabled: true,
        },
    };
    exports.PROCEED_FORM_DEFAULT = {
        builderDivisionField: {
            id: "custpage_builderdivision",
            label: "Builder Division",
            source: "customer",
            type: serverWidget.FieldType.SELECT,
            displayType: serverWidget.FieldDisplayType.DISABLED,
            disabled: true,
            relatedField: exports.PROPERTY_RECORD.builderDivision,
        },
        address: {
            id: "custpage_address",
            label: "Address",
            source: null,
            type: serverWidget.FieldType.TEXT,
            displayType: serverWidget.FieldDisplayType.DISABLED,
            disabled: true,
            relatedField: exports.PROPERTY_RECORD.address,
        },
        subdivisionNameField: {
            id: "custpage_sub_division",
            label: "Subdivision Name",
            source: "customrecord_subdivision",
            type: serverWidget.FieldType.SELECT,
            displayType: serverWidget.FieldDisplayType.DISABLED,
            disabled: true,
            relatedField: exports.PROPERTY_RECORD.subdivisionName,
        },
        lotNumberField: {
            id: "custpage_lotnumber",
            label: "Lot Number",
            source: null,
            type: serverWidget.FieldType.TEXT,
            displayType: serverWidget.FieldDisplayType.DISABLED,
            disabled: true,
            relatedField: exports.PROPERTY_RECORD.lotNumber,
        },
        saleStatusField: {
            id: "custpage_salesstatus",
            label: "New Sales Status",
            source: null,
            type: serverWidget.FieldType.SELECT,
            displayType: serverWidget.FieldDisplayType.DISABLED,
            disabled: true,
            relatedField: null,

        },
        mlsRegion1: {
            id: "custpage_mls_region1",
            label: "MLS Region 1",
            source: "location",
            type: serverWidget.FieldType.SELECT,
            displayType: serverWidget.FieldDisplayType.DISABLED,
            disabled: true,
            relatedField: exports.PROPERTY_RECORD.mlsRegion1,
        },
        mlsNumberRegion1: {
            id: "custpage_mls_no_reg1",
            label: "MLS Number - Region 1",
            source: null,
            type: serverWidget.FieldType.TEXT,
            displayType: serverWidget.FieldDisplayType.DISABLED,
            disabled: true,
            relatedField: exports.PROPERTY_RECORD.mlsNumberRegion1,
        },
        mlsRegion2: {
            id: "custpage_mls_region2",
            label: "MLS Region 2",
            source: "location",
            type: serverWidget.FieldType.SELECT,
            displayType: serverWidget.FieldDisplayType.DISABLED,
            disabled: true,
            relatedField: exports.PROPERTY_RECORD.mlsRegion2,
        },
        mlsNumberRegion2: {
            id: "custpage_mls_no_reg2",
            label: "MLS Number - Region 2",
            source: null,
            type: serverWidget.FieldType.TEXT,
            displayType: serverWidget.FieldDisplayType.DISABLED,
            disabled: true,
            relatedField: exports.PROPERTY_RECORD.mlsNumberRegion2,
            hideIfNullField: exports.PROPERTY_RECORD.mlsRegion2,
        },
    };
    exports.AVAILABLE_TO_PENDING_FORM = {
        contractApprovalDateField: {
            id: "custpage_contract_approval_date",
            label: "Contract Approval Date",
            source: null,
            type: serverWidget.FieldType.DATE,
            disabled: false,
            mandatory: true,
            relatedField: exports.PROPERTY_RECORD.contractApprovalDate,
        },
        contractReceivedFromBuilderField: {
            id: "custpage_contract_receive_from_builder",
            label: "Contract Received From Builder",
            source: null,
            type: serverWidget.FieldType.DATE,
            disabled: false,
            mandatory: true,
            relatedField: exports.PROPERTY_RECORD.contractReceiveFromBuilder,
        },
        estimatedClosingDateField: {
            id: "custpage_estimated_closing_date",
            label: "Estimated Closing Date",
            source: null,
            type: serverWidget.FieldType.DATE,
            disabled: false,
            relatedField: exports.PROPERTY_RECORD.estimatedClosingDate,
        },
        primaryRealEstateAgentName: {
            id: "custpage_primary_agent_name",
            label: "Primary Real Estate Agent Name",
            source: "customrecord_agent",
            type: serverWidget.FieldType.SELECT,
            disabled: false,
            relatedField: exports.PROPERTY_RECORD.primaryRealEstateAgentName,
            newColumn: true,
        },
        primaryAgentId: {
            id: "custpage_primary_agent_id",
            label: "Primary Real Estate Agent ID",
            source: null,
            type: serverWidget.FieldType.TEXT,
            displayType: serverWidget.FieldDisplayType.DISABLED,
            disabled: true,
            relatedField: exports.PROPERTY_RECORD.primaryRealEstateAgentId,
        },
        brokerageName: {
            id: "custpage_brokerage_name",
            label: "Real Estate Brokerage Name",
            source: "customrecordbrokerage",
            type: serverWidget.FieldType.SELECT,
            disabled: false,
            relatedField: exports.PROPERTY_RECORD.brokerageName,
        },
        brokerageId: {
            id: "custpage_brokerage_id",
            label: "Real Estate Brokerage ID",
            source: null,
            type: serverWidget.FieldType.TEXT,
            displayType: serverWidget.FieldDisplayType.DISABLED,
            disabled: true,
            relatedField: exports.PROPERTY_RECORD.brokerageId,
        },
        additionalAgentName: {
            id: "custpage_additional_agent_name",
            label: "Additional Real Estate Agent Name",
            source: "customrecord_agent",
            type: serverWidget.FieldType.SELECT,
            disabled: false,
            relatedField: exports.PROPERTY_RECORD.additonalRealEstateAgentName,
        },
        additionalAgentId: {
            id: "custpage_additional_agent_id",
            label: "Additional Real Estate Agent ID",
            source: null,
            type: serverWidget.FieldType.TEXT,
            displayType: serverWidget.FieldDisplayType.DISABLED,
            disabled: true,
            relatedField: exports.PROPERTY_RECORD.additonalRealEstateAgentId,
        },
        additionalAgentRole: {
            id: "custpage_additional_agent_role",
            label: "Additional Real Estate Agent Role",
            source: null,
            type: serverWidget.FieldType.TEXT,
            displayType: serverWidget.FieldDisplayType.DISABLED,
            disabled: true,
            relatedField: exports.PROPERTY_RECORD.additinalRealEstateAgentRole,
        },
        buyersName: {
            id: "custpage_buyer_name",
            label: "Buyer Name",
            source: null,
            type: serverWidget.FieldType.TEXT,
            disabled: false,
            mandatory: true,
            relatedField: exports.PROPERTY_RECORD.buyersName,
        },
        primaryRealEstateAgentNameFreeForm: {
            id: "custpage_primary_agent_name_free_form",
            label: "Primary Agent Name - Free Form Text",
            source: null,
            type: serverWidget.FieldType.TEXT,
            displayType: serverWidget.FieldDisplayType.DISABLED,
            disabled: true,
            relatedField: exports.PROPERTY_RECORD.primaryRealEstateAgentNameFreeForm,
            newColumn: true,
        },
        primaryAgentIdFreeForm: {
            id: "custpage_sales_notification_agent_id_free_form",
            label: "Primary Agent ID - Free Form Text",
            source: null,
            type: serverWidget.FieldType.TEXT,
            displayType: serverWidget.FieldDisplayType.DISABLED,
            disabled: true,
            relatedField: exports.PROPERTY_RECORD.primaryAgentIdFreeForm,
        },
        brokerageNameFreeForm: {
            id: "custpage_broker_name_free_form",
            label: "Brokerage Name - Free Form Text",
            source: null,
            type: serverWidget.FieldType.TEXT,
            displayType: serverWidget.FieldDisplayType.DISABLED,
            disabled: true,
            relatedField: exports.PROPERTY_RECORD.brokerageNameFreeForm,
        },
        additonalRealEstateAgentNameFreeForm: {
            id: "custpage_additional_agent_name_free_form",
            label: "Additional Agent Name - Free Form Text",
            source: null,
            type: serverWidget.FieldType.TEXT,
            displayType: serverWidget.FieldDisplayType.DISABLED,
            disabled: true,
            relatedField: exports.PROPERTY_RECORD.additonalRealEstateAgentNameFreeForm,
        },
        additionalAgentIdFreeForm: {
            id: "custpage_additional_agent_id_free_form",
            label: "Additional Agent ID - Free Form Text",
            source: null,
            type: serverWidget.FieldType.TEXT,
            displayType: serverWidget.FieldDisplayType.DISABLED,
            disabled: true,
            relatedField: exports.PROPERTY_RECORD.additonalRealEstateAgentIdFreeForm,
        },
        sellingTeamName: {
            id: "custpage_selling_team_name",
            label: "Selling Team Name",
            source: null,
            type: serverWidget.FieldType.TEXT,
            displayType: serverWidget.FieldDisplayType.DISABLED,
            disabled: true,
            relatedField: exports.PROPERTY_RECORD.sellingTeamName,
        },
        /* enterSaleAsTeam: {
            id: "custpage_enter_sale_as_team",
            label: "Enter Sale as Team",
            source: null,
            type: serverWidget.FieldType.CHECKBOX,
            displayType: serverWidget.FieldDisplayType.DISABLED,
        disabled: true,

            relatedField: PROPERTY_RECORD.enterSaleAsTeam,
        }, */
        saleNotes: {
            id: "custpage_sales_notes",
            label: "Sale Notes",
            source: null,
            type: serverWidget.FieldType.TEXTAREA,
            disabled: false,
            relatedField: exports.PROPERTY_RECORD.salesNotes,
        },
        sellingAgentComments: {
            id: "custpage_selling_agent_comments",
            label: "Selling Agent Comments",
            source: null,
            type: serverWidget.FieldType.TEXTAREA,
            displayType: serverWidget.FieldDisplayType.DISABLED,
            disabled: true,
            relatedField: exports.PROPERTY_RECORD.sellingAgentComments,
        },
        purchaseContract: {
            id: "custpage_purchase_contract",
            label: "Purchase Contract",
            source: null,
            type: serverWidget.FieldType.FILE,
            relatedField: exports.PROPERTY_RECORD.purchaseContact,
        },
        pendingNotificationDateMLSRegion1: {
            id: "custpage_pending_notification1",
            label: "Pending Notification Date MLS Region 1",
            source: null,
            type: serverWidget.FieldType.DATE,
            disabled: false,
            mandatory: true,
            relatedField: exports.PROPERTY_RECORD.pendingNotificationDateMLSRegion1,
        },
        pendingPrintfull1: {
            id: "custpage_pending_printfull1",
            label: "Printfull MLS Region 1",
            source: null,
            type: serverWidget.FieldType.FILE,
            relatedField: exports.PROPERTY_RECORD.pendingPrintfull1,
        },
        pendingNotificationDateMLSRegion2: {
            id: "custpage_pending_notification2",
            label: "Pending Notification Date MLS Region 2",
            source: null,
            type: serverWidget.FieldType.DATE,
            disabled: false,
            relatedField: exports.PROPERTY_RECORD.pendingNotificationDateMLSRegion2,
        },
        pendingPrintfull2: {
            id: "custpage_pending_printfull2",
            label: "Printfull MLS Region 2",
            source: null,
            type: serverWidget.FieldType.FILE,
            relatedField: exports.PROPERTY_RECORD.pendingPrintfull2,
        },
    };
    exports.BACK_ON_MARKET_FORM = {
        contractApprovalDateField: {
            id: "custpage_contract_approval_date",
            label: "Contract Approval Date",
            source: null,
            type: serverWidget.FieldType.DATE,
            disabled: false,
            displayType: serverWidget.FieldDisplayType.HIDDEN,
            relatedField: exports.PROPERTY_RECORD.contractApprovalDate,
        },
        estimatedClosingPriceField: {
            id: "custpage_estimated_closing_price",
            label: "Estimated Closing Price",
            source: null,
            type: serverWidget.FieldType.CURRENCY,
            displayType: serverWidget.FieldDisplayType.HIDDEN,
            relatedField: exports.PROPERTY_RECORD.estimatedClosingPrice,
        },
        contractReceivedFromBuilderField: {
            id: "custpage_contract_receive_from_builder",
            label: "Contract Received From Builder",
            source: null,
            type: serverWidget.FieldType.DATE,
            disabled: false,
            displayType: serverWidget.FieldDisplayType.HIDDEN,
            relatedField: exports.PROPERTY_RECORD.contractReceiveFromBuilder,
        },
        constructionStatusAtContract: {
            id: "custpage_construction_status_at_contract",
            label: "Construction Status at Contract",
            source: null,
            type: serverWidget.FieldType.SELECT,
            disabled: false,
            displayType: serverWidget.FieldDisplayType.HIDDEN,
            relatedField: exports.PROPERTY_RECORD.constructionStatusAtContract,
        },
        estimatedClosingDateField: {
            id: "custpage_estimated_closing_date",
            label: "Estimated Closing Date",
            source: null,
            type: serverWidget.FieldType.DATE,
            disabled: false,
            displayType: serverWidget.FieldDisplayType.HIDDEN,
            relatedField: exports.PROPERTY_RECORD.estimatedClosingDate,
        },
        primaryRealEstateAgentName: {
            id: "custpage_primary_agent_name",
            label: "Primary Real Estate Agent Name",
            source: "customrecord_agent",
            type: serverWidget.FieldType.SELECT,
            disabled: false,
            displayType: serverWidget.FieldDisplayType.HIDDEN,
            relatedField: exports.PROPERTY_RECORD.primaryRealEstateAgentName,
            newColumn: true,
        },
        primaryAgentId: {
            id: "custpage_primary_agent_id",
            label: "Primary Real Estate Agent ID",
            source: null,
            type: serverWidget.FieldType.TEXT,
            displayType: serverWidget.FieldDisplayType.HIDDEN,
            relatedField: exports.PROPERTY_RECORD.primaryRealEstateAgentId,
        },
        brokerageName: {
            id: "custpage_brokerage_name",
            label: "Real Estate Brokerage Name",
            source: "customrecordbrokerage",
            type: serverWidget.FieldType.SELECT,
            disabled: false,
            displayType: serverWidget.FieldDisplayType.HIDDEN,
            relatedField: exports.PROPERTY_RECORD.brokerageName,
        },
        brokerageId: {
            id: "custpage_brokerage_id",
            label: "Real Estate Brokerage ID",
            source: null,
            type: serverWidget.FieldType.TEXT,
            displayType: serverWidget.FieldDisplayType.HIDDEN,
            relatedField: exports.PROPERTY_RECORD.brokerageId,
        },
        additionalAgentName: {
            id: "custpage_additional_agent_name",
            label: "Additional Real Estate Agent Name",
            source: "customrecord_agent",
            type: serverWidget.FieldType.SELECT,
            disabled: false,
            displayType: serverWidget.FieldDisplayType.HIDDEN,
            relatedField: exports.PROPERTY_RECORD.additonalRealEstateAgentName,
        },
        additionalAgentId: {
            id: "custpage_additional_agent_id",
            label: "Additional Real Estate Agent ID",
            source: null,
            type: serverWidget.FieldType.TEXT,
            displayType: serverWidget.FieldDisplayType.HIDDEN,
            relatedField: exports.PROPERTY_RECORD.additonalRealEstateAgentId,
        },
        additionalAgentRole: {
            id: "custpage_additional_agent_role",
            label: "Additional Real Estate Agent Role",
            source: null,
            type: serverWidget.FieldType.TEXT,
            displayType: serverWidget.FieldDisplayType.HIDDEN,
            relatedField: exports.PROPERTY_RECORD.additinalRealEstateAgentRole,
        },
        buyersName: {
            id: "custpage_buyer_name",
            label: "Buyer Name",
            source: null,
            type: serverWidget.FieldType.TEXT,
            disabled: false,
            displayType: serverWidget.FieldDisplayType.HIDDEN,
            relatedField: exports.PROPERTY_RECORD.buyersName,
        },
        primaryRealEstateAgentNameFreeForm: {
            id: "custpage_primary_agent_name_free_form",
            label: "Primary Agent Name - Free Form Text",
            source: null,
            type: serverWidget.FieldType.TEXT,
            displayType: serverWidget.FieldDisplayType.HIDDEN,
            relatedField: exports.PROPERTY_RECORD.primaryRealEstateAgentNameFreeForm,
            newColumn: true,
        },
        primaryAgentIdFreeForm: {
            id: "custpage_sales_notification_agent_id_free_form",
            label: "Primary Agent ID - Free Form Text",
            source: null,
            type: serverWidget.FieldType.TEXT,
            displayType: serverWidget.FieldDisplayType.HIDDEN,
            relatedField: exports.PROPERTY_RECORD.primaryAgentIdFreeForm,
        },
        brokerageNameFreeForm: {
            id: "custpage_broker_name_free_form",
            label: "Brokerage Name - Free Form Text",
            source: null,
            type: serverWidget.FieldType.TEXT,
            displayType: serverWidget.FieldDisplayType.HIDDEN,
            relatedField: exports.PROPERTY_RECORD.brokerageNameFreeForm,
        },
        additonalRealEstateAgentNameFreeForm: {
            id: "custpage_additional_agent_name_free_form",
            label: "Additional Agent Name - Free Form Text",
            source: null,
            type: serverWidget.FieldType.TEXT,
            displayType: serverWidget.FieldDisplayType.HIDDEN,
            relatedField: exports.PROPERTY_RECORD.additonalRealEstateAgentNameFreeForm,
        },
        additionalAgentIdFreeForm: {
            id: "custpage_additional_agent_id_free_form",
            label: "Additional Agent ID - Free Form Text",
            source: null,
            type: serverWidget.FieldType.TEXT,
            displayType: serverWidget.FieldDisplayType.HIDDEN,
            relatedField: exports.PROPERTY_RECORD.additonalRealEstateAgentIdFreeForm,
        },
        sellingTeamName: {
            id: "custpage_selling_team_name",
            label: "Selling Team Name",
            source: null,
            type: serverWidget.FieldType.TEXT,
            displayType: serverWidget.FieldDisplayType.HIDDEN,
            relatedField: exports.PROPERTY_RECORD.sellingTeamName,
        },
        enterSaleAsTeam: {
            id: "custpage_enter_sale_as_team",
            label: "Enter Sale as Team",
            source: null,
            type: serverWidget.FieldType.CHECKBOX,
            displayType: serverWidget.FieldDisplayType.HIDDEN,
            relatedField: exports.PROPERTY_RECORD.enterSaleAsTeam,
        },
        saleNotes: {
            id: "custpage_sales_notes",
            label: "Sale Notes",
            source: null,
            type: serverWidget.FieldType.TEXTAREA,
            disabled: false,
            displayType: serverWidget.FieldDisplayType.HIDDEN,
            relatedField: exports.PROPERTY_RECORD.salesNotes,
        },
        sellingAgentComments: {
            id: "custpage_selling_agent_comments",
            label: "Selling Agent Comments",
            source: null,
            type: serverWidget.FieldType.TEXTAREA,
            displayType: serverWidget.FieldDisplayType.HIDDEN,
            relatedField: exports.PROPERTY_RECORD.sellingAgentComments,
        },
        purchaseContract: {
            id: "custpage_purchase_contract",
            label: "Purchase Contract",
            source: null,
            type: serverWidget.FieldType.TEXT,
            displayType: serverWidget.FieldDisplayType.HIDDEN,
            relatedField: exports.PROPERTY_RECORD.purchaseContact,
        },
        pendingNotificationDateMLSRegion1: {
            id: "custpage_pending_notification1",
            label: "Pending Notification Date MLS Region 1",
            source: null,
            type: serverWidget.FieldType.DATE,
            disabled: false,
            displayType: serverWidget.FieldDisplayType.HIDDEN,
            relatedField: exports.PROPERTY_RECORD.pendingNotificationDateMLSRegion1,
        },
        pendingPrintfull1: {
            id: "custpage_pending_printfull1",
            label: "Printfull MLS Region 1",
            source: null,
            type: serverWidget.FieldType.TEXT,
            displayType: serverWidget.FieldDisplayType.HIDDEN,
            relatedField: exports.PROPERTY_RECORD.pendingPrintfull1,
        },
        pendingNotificationDateMLSRegion2: {
            id: "custpage_pending_notification2",
            label: "Pending Notification Date MLS Region 2",
            source: null,
            type: serverWidget.FieldType.DATE,
            disabled: false,
            displayType: serverWidget.FieldDisplayType.HIDDEN,
            relatedField: exports.PROPERTY_RECORD.pendingNotificationDateMLSRegion2,
        },
        closedPrintfull2: {
            id: "custpage_closed_printfull2",
            label: "BOM Printfull",
            source: null,
            type: serverWidget.FieldType.FILE,
            disabled: false,
            relatedField: exports.PROPERTY_RECORD.closedPrintfull2,
        },
        currentConstructionStatus: {
            id: "custpage_current_cnsrtction_status",
            label: "Current Construction Status",
            source: "customlist_construction_status",
            type: serverWidget.FieldType.SELECT,
            disabled: false,
            relatedField: exports.PROPERTY_RECORD.currentConstructionStatus,
            keep: true,
        },
        currentListPrice: {
            id: "custpage_current_list_price",
            label: "Back on Market List Price",
            source: "custrecord_current_list_price",
            type: serverWidget.FieldType.CURRENCY,
            disabled: false,
            mandatory: true,
            relatedField: exports.PROPERTY_RECORD.currentListPrice,
            keep: true,
        },
        listingtype: {
            id: "custpage_listing_type",
            label: "Listing Type",
            source: "customlist_listing_type",
            type: serverWidget.FieldType.SELECT,
            disabled: false,
            mandatory: false,
            relatedField: exports.PROPERTY_RECORD.listingType,
            keep: true,
        },
        sellingBsr: {
            id: "custpage_selling_bsr",
            label: "Selling BSR",
            source: "custrecord_selling_bsr",
            type: serverWidget.FieldType.SELECT,
            displayType: serverWidget.FieldDisplayType.HIDDEN,
            relatedField: exports.PROPERTY_RECORD.sellingBsr,
        },
        saleSubmittedBy: {
            id: "custpage_mw_sale_submitted_by",
            label: "Sale Submitted By",
            source: "custrecord_mw_sale_submitted_by",
            type: serverWidget.FieldType.SELECT,
            displayType: serverWidget.FieldDisplayType.HIDDEN,
            relatedField: exports.PROPERTY_RECORD.saleSubmittedBy,
        },
        lender: {
            id: "custpage_financing_company",
            label: "Lender",
            source: "custrecord_financing_company,",
            type: serverWidget.FieldType.TEXT,
            displayType: serverWidget.FieldDisplayType.HIDDEN,
            relatedField: exports.PROPERTY_RECORD.lender,
        },
    };
    exports.PENDING_AWAITING_CONTRACT_FORM = {
        currentListPrice: {
            id: "custpage_current_list_price",
            label: "Current List Price",
            source: "custrecord_current_list_price",
            type: serverWidget.FieldType.TEXT,
            disabled: false,
            relatedField: exports.PROPERTY_RECORD.currentListPrice,
        },
        contractApprovalDateField: {
            id: "custpage_contract_approval_date",
            label: "Contract Approval Date (If known)",
            source: null,
            type: serverWidget.FieldType.DATE,
            disabled: false,
            relatedField: exports.PROPERTY_RECORD.contractApprovalDate,
        },
        estimatedClosingDateField: {
            id: "custpage_estimated_closing_date",
            label: "Estimated Closing Date (If known)",
            source: null,
            type: serverWidget.FieldType.DATE,
            disabled: false,
            relatedField: exports.PROPERTY_RECORD.estimatedClosingDate,
        },
        saleNotes: {
            id: "custpage_sales_notes",
            label: "Sale Notes",
            source: null,
            type: serverWidget.FieldType.TEXTAREA,
            disabled: false,
            relatedField: exports.PROPERTY_RECORD.salesNotes,
        },
    };
    exports.CLOSED_STATUS_FORM = {
        currentListPrice: {
            id: "custpage_current_list_price",
            label: "Current List Price",
            source: "custrecord_current_list_price",
            type: serverWidget.FieldType.TEXT,
            displayType: serverWidget.FieldDisplayType.DISABLED,
            disabled: true,
            relatedField: exports.PROPERTY_RECORD.currentListPrice,
        },
        buyersName: {
            id: "custpage_buyer_name",
            label: "Buyer",
            source: null,
            type: serverWidget.FieldType.TEXT,
            disabled: false,
            mandatory: true,
            relatedField: exports.PROPERTY_RECORD.buyersName,
        },
        closingPrice: {
            id: "custpage_closing_price",
            label: "Closing Price",
            source: null,
            type: serverWidget.FieldType.INTEGER,
            disabled: false,
            mandatory: true,
            relatedField: exports.PROPERTY_RECORD.closingPrice,
        },
        actualClosingDate: {
            id: "custpage_actual_closing_date",
            label: "Actual Closing Date",
            source: null,
            type: serverWidget.FieldType.DATE,
            disabled: false,
            mandatory: true,
            relatedField: exports.PROPERTY_RECORD.actualClosingDate,
        },
        sellerPaidClosingCosts: {
            id: "custpage_seller_paid_closing_costs",
            label: "Seller Paid Costs on Behalf of Buyer",
            source: null,
            type: serverWidget.FieldType.INTEGER,
            disabled: false,
            relatedField: exports.PROPERTY_RECORD.sellerPaidClosingCosts,
        },
        concessions: {
            id: "custpage_concessions",
            label: "Concessions",
            source: null,
            type: serverWidget.FieldType.TEXTAREA,
            disabled: false,
            relatedField: exports.PROPERTY_RECORD.concessions,
        },
        financingType: {
            id: "custpage_financing_type",
            label: "Financing Type",
            source: "customlist_financing_type",
            type: serverWidget.FieldType.SELECT,
            disabled: false,
            mandatory: true,
            relatedField: exports.PROPERTY_RECORD.financingType,
        },
        primaryRealEstateAgentName: {
            id: "custpage_primary_agent_name",
            label: "Primary Agent Name",
            source: "customrecord_agent",
            type: serverWidget.FieldType.SELECT,
            disabled: false,
            relatedField: exports.PROPERTY_RECORD.primaryRealEstateAgentName,
        },
        primaryRealEstateAgentID: {
            id: "custpage_primary_real_estate_agent_id",
            label: "Primary real Estate Agent ID",
            source: "custrecord_real_estate_agent_id_region_1",
            type: serverWidget.FieldType.TEXT,
            disabled: true,
            relatedField: exports.PROPERTY_RECORD.primaryRealEstateAgentId,
        },
        brokerageName: {
            id: "custpage_brokerage_name",
            label: "Brokerage Name",
            source: "customrecordbrokerage",
            type: serverWidget.FieldType.SELECT,
            disabled: false,
            relatedField: exports.PROPERTY_RECORD.brokerageName,
        },
        closingNotes: {
            id: "custpage_closing_notes",
            label: "Closing Notes",
            source: null,
            type: serverWidget.FieldType.LONGTEXT,
            disabled: false,
            relatedField: exports.PROPERTY_RECORD.closingNotes,
        },
        hudReceivedDate: {
            id: "custpage_hud_rcvd_date",
            label: "HUD Received Date",
            source: null,
            type: serverWidget.FieldType.DATE,
            disabled: false,
            mandatory: false,
            relatedField: exports.PROPERTY_RECORD.hudRcvdDate,
        },
        hud1: {
            id: "custpage_hud1",
            label: "Closing Disclosure/HUD",
            source: null,
            type: serverWidget.FieldType.FILE,
            disabled: false,
            mandatory: false,
            relatedField: exports.PROPERTY_RECORD.hud1,
        },
        closingNotificationDateMLSRegion1: {
            id: "custpage_closing_notify_date1",
            label: "Closing Notification Date MLS Region 1",
            source: null,
            type: serverWidget.FieldType.DATE,
            disabled: false,
            relatedField: exports.PROPERTY_RECORD.closingNotifyDate1,
        },
        closedPrintfull1: {
            id: "custpage_closed_printfull1",
            label: "Printfull MLS Region 1",
            source: null,
            type: serverWidget.FieldType.FILE,
            disabled: false,
            mandatory: true,
            relatedField: exports.PROPERTY_RECORD.closedPrintfull1,
        },
        closingNotificationDateMLSRegion2: {
            id: "custpage_closing_notify_date2",
            label: "Closing Notification Date MLS Region 2",
            source: null,
            type: serverWidget.FieldType.DATE,
            disabled: false,
            relatedField: exports.PROPERTY_RECORD.closingNotifyDate2,
        },
        closedPrintfull2: {
            id: "custpage_closed_printfull2",
            label: "Printfull MLS Region 2",
            source: null,
            type: serverWidget.FieldType.FILE,
            disabled: false,
            relatedField: exports.PROPERTY_RECORD.closedPrintfull2,
        },
    };
    exports.CANCEL_WITHDRAWAL_FORM = {
        originalListPrice: {
            id: "custpage_original_list_price",
            label: "Original List Price",
            source: null,
            type: serverWidget.FieldType.CURRENCY,
            disabled: false,
            relatedField: exports.PROPERTY_RECORD.originalListPrice,
        },
        constructionStatusAtListing: {
            id: "custpage_construction_status_list",
            label: "Construction Status at Listing",
            source: "customlist_construction_status",
            type: serverWidget.FieldType.SELECT,
            disabled: false,
            relatedField: exports.PROPERTY_RECORD.constructionStatusList,
        },
        listDate: {
            id: "custpage_list_date",
            label: "List Date",
            source: null,
            type: serverWidget.FieldType.DATE,
            disabled: false,
            relatedField: exports.PROPERTY_RECORD.listDate,
        },
        estimatedUnderRoofDate: {
            id: "custpage_estimate_roof_date",
            label: "Estimated Under Roof Date",
            source: null,
            type: serverWidget.FieldType.DATE,
            disabled: false,
            relatedField: exports.PROPERTY_RECORD.estimateRoofDate,
        },
        estimatedCompletionDate: {
            id: "custpage_estimate_completion_date",
            label: "Estimated Completion Date",
            source: null,
            type: serverWidget.FieldType.DATE,
            disabled: false,
            relatedField: exports.PROPERTY_RECORD.estimateCompletionDate,
        },
        currentListPrice: {
            id: "custpage_current_list_price",
            label: "Current List Price",
            source: null,
            type: serverWidget.FieldType.CURRENCY,
            disabled: false,
            relatedField: exports.PROPERTY_RECORD.currentListPrice,
        },
        currentConstructionStatus: {
            id: "custpage_current_cnsrtction_status",
            label: "Current Construction Status",
            source: "customlist_construction_status",
            type: serverWidget.FieldType.SELECT,
            disabled: false,
            relatedField: exports.PROPERTY_RECORD.currentConstructionStatus,
        },
        /*     mlsRegion1: {
            id: "custpage_mls_region1",
            label: "MLS Region 1",
            source: "location",
            type: serverWidget.FieldType.SELECT,
            disabled: false,
            relatedField: PROPERTY_RECORD.mlsRegion1,
        }, */
        listingNotificationDateMLSRegion1: {
            id: "custpage_list_notify_mls_region1",
            label: "Listing Notification Date MLS Region 1",
            source: null,
            type: serverWidget.FieldType.DATE,
            disabled: false,
            relatedField: exports.PROPERTY_RECORD.listNotifyMlsRegion1,
        },
        /*     mlsRegion2: {
            id: "custpage_mls_region2",
            label: "MLS Region 2",
            source: "location",
            type: serverWidget.FieldType.SELECT,
            disabled: false,
            relatedField: PROPERTY_RECORD.mlsRegion2,
        }, */
        listingNotificationDateMLSRegion2: {
            id: "custpage_list_notify_mls_region2",
            label: "Listing Notification Date MLS Region 2",
            source: null,
            type: serverWidget.FieldType.DATE,
            disabled: false,
            relatedField: exports.PROPERTY_RECORD.listNotifyMlsRegion2,
        },
        expirationDate: {
            id: "custpage_expiration_date",
            label: "Expiration Date",
            source: null,
            type: serverWidget.FieldType.DATE,
            disabled: false,
            relatedField: exports.PROPERTY_RECORD.expirationDate,
        },
        floorplan: {
            id: "custpage_floorplan",
            label: "Floorplan",
            source: "customrecord_floorplan",
            type: serverWidget.FieldType.SELECT,
            disabled: false,
            relatedField: exports.PROPERTY_RECORD.floorplan,
        },
        elevation: {
            id: "custpage_elevation",
            label: "Elevation",
            source: null,
            type: serverWidget.FieldType.TEXT,
            disabled: false,
            relatedField: exports.PROPERTY_RECORD.elevation,
        },
        squareFeet: {
            id: "custpage_square_feet",
            label: "Square Feet",
            source: null,
            type: serverWidget.FieldType.INTEGER,
            disabled: false,
            relatedField: exports.PROPERTY_RECORD.squareFeet,
        },
        propertyPhotos: {
            id: "custpage_property_photos",
            label: "Property Photos",
            source: null,
            type: serverWidget.FieldType.URL,
            disabled: false,
            relatedField: exports.PROPERTY_RECORD.propertyPhotos,
        },
        listingNotes: {
            id: "custpage_listing_notes",
            label: "Listing Notes",
            // WithdrawnOrCanceledForm
            label2: "Reason for Cancellation/Withdrawal",
            source: null,
            type: serverWidget.FieldType.LONGTEXT,
            disabled: false,
            relatedField: exports.PROPERTY_RECORD.listingNotes,
        },
        /*     mlsNumberRegion1: {
            id: "custpage_mls_no_reg1",
            label: "MLS Number - Region 1",
            source: null,
            type: serverWidget.FieldType.TEXT,
            disabled: false,
            relatedField: PROPERTY_RECORD.mlsNumberRegion1,
        },
        mlsNumberRegion2: {
            id: "custpage_mls_no_reg2",
            label: "MLS Number - Region 2",
            source: null,
            type: serverWidget.FieldType.TEXT,
            disabled: false,
            relatedField: PROPERTY_RECORD.mlsNumberRegion2,
        }, */
        currentListPriceInit: {
            id: "custpage_current_list_price_init",
            label: "Price Init",
            source: null,
            type: serverWidget.FieldType.TEXT,
            disabled: false,
            relatedField: exports.PROPERTY_RECORD.currentListPrice,
            displayType: serverWidget.FieldDisplayType.HIDDEN,
        },
        addNewAmedment: {
            id: "custpage_create_amedment",
            label: "Create Amedment?",
            source: null,
            type: serverWidget.FieldType.TEXT,
            disabled: false,
            relatedField: "",
            displayType: serverWidget.FieldDisplayType.HIDDEN,
        },
    };
    function getPropertyFolder(pFolderPath, pParentId) {
        var folderId = null;
        var folderFilters = [];
        folderFilters.push({ name: "name", operator: "is", values: [pFolderPath] });
        pParentId
            ? folderFilters.push({
                name: "parent",
                operator: "anyof",
                values: [pParentId],
            })
            : folderFilters.push({
                name: "istoplevel",
                operator: "is",
                values: true,
            });
        log.debug("getPropertyFolder", "pFolderPath : '".concat(pFolderPath, "', pParentId :'").concat(pParentId, "', folderFilters : ").concat(JSON.stringify(folderFilters)));
        search
            .create({ type: search.Type.FOLDER, filters: folderFilters })
            .run()
            .each(function (folder) {
            folderId = folder.id;
            return false;
        });
        if (!folderId) {
            var folderRecord = record.create({ type: record.Type.FOLDER });
            folderRecord.setValue({ fieldId: "name", value: pFolderPath });
            folderRecord.setValue({ fieldId: "parent", value: pParentId });
            folderId = folderRecord.save();
        }
        return folderId;
    }
});
